TRUNCATE TABLE users RESTART IDENTITY CASCADE;

TRUNCATE TABLE wallets RESTART IDENTITY CASCADE;

TRUNCATE TABLE user_roles RESTART IDENTITY CASCADE;

TRUNCATE TABLE games RESTART IDENTITY CASCADE;


TRUNCATE TABLE shop RESTART IDENTITY CASCADE;

TRUNCATE TABLE game_genres RESTART IDENTITY CASCADE;

TRUNCATE TABLE transactions RESTART IDENTITY CASCADE;

TRUNCATE TABLE library RESTART IDENTITY CASCADE;

TRUNCATE TABLE items RESTART IDENTITY CASCADE;

TRUNCATE TABLE inventory RESTART IDENTITY CASCADE;

TRUNCATE TABLE user_activity RESTART IDENTITY CASCADE;

TRUNCATE TABLE guides RESTART IDENTITY CASCADE;

TRUNCATE TABLE market RESTART IDENTITY CASCADE;


