TRUNCATE TABLE  "Пользователь" RESTART IDENTITY CASCADE;

TRUNCATE TABLE  "Разработчик" RESTART IDENTITY CASCADE;

TRUNCATE TABLE  "Игра" RESTART IDENTITY CASCADE;

TRUNCATE TABLE  "Группа" RESTART IDENTITY CASCADE;

TRUNCATE TABLE  "Кошелек" RESTART IDENTITY;

TRUNCATE TABLE  "Транзакции" RESTART IDENTITY;

TRUNCATE TABLE  "Список сообщений" RESTART IDENTITY;

TRUNCATE TABLE  "Магазин" RESTART IDENTITY;

TRUNCATE TABLE  "Внутриигровая вещь" RESTART IDENTITY CASCADE;

TRUNCATE TABLE  "Торговая площадка" RESTART IDENTITY;

TRUNCATE TABLE  "Инвентарь" RESTART IDENTITY;

TRUNCATE TABLE  "Библиотека" RESTART IDENTITY;

TRUNCATE TABLE "Руководство" RESTART IDENTITY;

TRUNCATE TABLE "Мастерская" RESTART IDENTITY;